// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkz6Goj2jTcyzjlOaIsBkiZn9N14K0u4',
    appId: '1:331230989768:web:9e52d0b9ad7a44b0b384fd',
    messagingSenderId: '331230989768',
    projectId: 'movie-app-e39c2',
    authDomain: 'movie-app-e39c2.firebaseapp.com',
    storageBucket: 'movie-app-e39c2.firebasestorage.app',
    measurementId: 'G-6VGQZMNBJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjR8al3ZqysXnxEcu-DnTD6R2J2zEUQIY',
    appId: '1:331230989768:android:605caac9d79e284eb384fd',
    messagingSenderId: '331230989768',
    projectId: 'movie-app-e39c2',
    storageBucket: 'movie-app-e39c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgh-VTDBHAvm3t9mOJgzfmdCejEAoJH3s',
    appId: '1:331230989768:ios:24fe3f799ac736beb384fd',
    messagingSenderId: '331230989768',
    projectId: 'movie-app-e39c2',
    storageBucket: 'movie-app-e39c2.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgh-VTDBHAvm3t9mOJgzfmdCejEAoJH3s',
    appId: '1:331230989768:ios:24fe3f799ac736beb384fd',
    messagingSenderId: '331230989768',
    projectId: 'movie-app-e39c2',
    storageBucket: 'movie-app-e39c2.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxkz6Goj2jTcyzjlOaIsBkiZn9N14K0u4',
    appId: '1:331230989768:web:cf64b4261fdecc71b384fd',
    messagingSenderId: '331230989768',
    projectId: 'movie-app-e39c2',
    authDomain: 'movie-app-e39c2.firebaseapp.com',
    storageBucket: 'movie-app-e39c2.firebasestorage.app',
    measurementId: 'G-TXE2LRD8CD',
  );

}