// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU134xSRcPrREO36cUhea8-s2jyIl_xao',
    appId: '1:651118685901:web:7af60090dcfe9204af8384',
    messagingSenderId: '651118685901',
    projectId: 'movie-app-a4cc6',
    authDomain: 'movie-app-a4cc6.firebaseapp.com',
    storageBucket: 'movie-app-a4cc6.firebasestorage.app',
    measurementId: 'G-99N5FYTPN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTH_qebGAAk3UN-4qSIxjbAM3I1o57rg',
    appId: '1:651118685901:android:4b2c3197f981f94caf8384',
    messagingSenderId: '651118685901',
    projectId: 'movie-app-a4cc6',
    storageBucket: 'movie-app-a4cc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gX4Fo6F8jySJFm2geQvkiAsoLhl_NXs',
    appId: '1:651118685901:ios:31bca7bef61edcccaf8384',
    messagingSenderId: '651118685901',
    projectId: 'movie-app-a4cc6',
    storageBucket: 'movie-app-a4cc6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4gX4Fo6F8jySJFm2geQvkiAsoLhl_NXs',
    appId: '1:651118685901:ios:31bca7bef61edcccaf8384',
    messagingSenderId: '651118685901',
    projectId: 'movie-app-a4cc6',
    storageBucket: 'movie-app-a4cc6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU134xSRcPrREO36cUhea8-s2jyIl_xao',
    appId: '1:651118685901:web:e46869ba2159c5ffaf8384',
    messagingSenderId: '651118685901',
    projectId: 'movie-app-a4cc6',
    authDomain: 'movie-app-a4cc6.firebaseapp.com',
    storageBucket: 'movie-app-a4cc6.firebasestorage.app',
    measurementId: 'G-C9WBY60VFZ',
  );
}
